define(function() {
    return {
        "properties": [{
            "name": "chartData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linesData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "intervalValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "xAxisTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "yAxisTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chartTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleFontColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleFontSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["createChart", "showGridChart"],
        "events": []
    }
});