define(function () {
  return {
    WRONG_USERNAME_OR_PASSWORD                        : " (CL001)",
    SERVICE_DOWN_GET_ACCOUNTS						  : " (CL002)",
    LOGIN_WRONG_FORMAT                                : " (CL003)",
    PARTYID_MISMATCHED                                : " (CL004)",
    SERVICE_DOWN_KPI                                  : " (CL005)",
    SERVICE_MDMS									  : " (CL006)",
    SERVICE_DOWN_MAGICBONUS                           : " (CL007)",
    SERVICE_DOWN_WSO2                                 : " (CL008)",
    SERVICE_DOWN_OCTA                                 : " (CL009)",
    SERVICE_DOWN_GATEWAY                              : " (CL010)",
    SERVICE_DOWN_ENVIORNMENTCROSSCHECK                : " (CL011)",
    SERVICE_DOWN_MICROSERVICES                        : " (CL012)",
    SERVICE_DOWN_MAGLOFT                              : " (CL013)",
    PAGE_TIME_OUT                                     : " (CL014)",
    SERVICE_DOWN_KONYMOBILEFABRIC                     : " (CL015)",
    LOGIN_VALIDATION_NETWORK_UNAVAILABLE              : " (CL016)",
    SERVICE_DOWN_PROFILE_IMAGE						  : " (CL017)",
    GET_RENEWAL_FAILURE								  : " (CL018)",
    DEVICE_NOT_SUPPORT_TOUCH_ID                       : " (CL019)",
    TOUCH_ID_NOT_MATCHING_FIVE_TIMES                  : " (CL021)",
    FACE_ID_DISABLED_IN_SETTINGS                      : " (CL022)",
    FACE_ID_NOT_MATCHING_FIVE_TIMES                   : " (CL023)",
    DEVICE_NOT_SUPPORT_FINGER_PRINT                   : " (CL024)",
    FINGER_PRINT_DISABLED_IN_SETTINGS                 : " (CL025)",
    FINGER_PRINT_NOT_MATCHING_FIVE_TIMES              : " (CL026)",
    SESSION_TIME_OUT                                  : " (CL028)",
    OBJECT_NOT_FOUND                                  : " (CL031)",
    REGISTER_COUNTRY_LANGUAGE_FAILURE                 : " (CL032)",
    MDMS_REGISTRATION_FAILURE                         : " (CL033)",
    MDMS_VALIDATION_FAILURE                           : " (CL034)",
    DOS_DATA_FAILURE								  : " (CL035)",
    LOGIN_ID_OAUTH									  : " (CL036)",
    CODE_CHECK_VALIDATION_FAILED					  : " (CL037)",
    FETCH_PAYLOAD_FAILED							  : " (CL038)",
  };
});
